{% set name = "mshr" %}
{% set version = "2018.1.0" %}
{% set sha256 = "c2f91300aff792de76b937e7e709076d8ac37043ddb6fe250ebb4229b48ac014" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://bitbucket.org/fenics-project/{{ name }}/downloads/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # Link boost_thread on macOS. Doesn't appear to be needed
    # on recent versions (10.12), but seems needed on Travis (Xcode 6.4, currently).
    - boost-thread.patch  # [osx]

build:
  number: 1
  skip: true  # [win or py2k]

requirements:
  build:
    - cmake
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - boost-cpp
    - python
    - pip
    - fenics {{version}}
    - gmp
    - mpfr
    - pybind11
  run:
    - boost-cpp
    - python
    - fenics {{version}}
    - gmp
    - mpfr

test:
  source_files:
    - test
  imports:
    - mshr

about:
  home: https://bitbucket.org/fenics-project/mshr
  license: GPL-3.0
  license_family: GPL3
  license_file: COPYING
  summary: mshr is the mesh generation component of FEniCS
  description: |
    mshr is the mesh generation component of FEniCS. It generates simplicial DOLFIN
    meshes in 2D and 3D from geometries described by Constructive Solid Geometry (CSG) or from
    surface files, utilizing CGAL and Tetgen as mesh generation backends.
  doc_url: http://fenics.readthedocs.io/projects/mshr
  dev_url: https://bitbucket.org/fenics-project/mshr

extra:
  recipe-maintainers:
    - minrk
    - jbweston
