travis:
  secure:
    BINSTAR_TOKEN: BzjrFgonic9OA0N0IgY7cX0GQOwvA89+5R32ICgKoHy8dw2jehPO+rhFnmftOGRWpW8nsbYDmq9Uzrwi03nVAMGNVhhn1vrnJPdjaMCODBqteJf8jVZzY523GfpqQRFfRoRQNFDx2w08hHPAbQLiC42FYtnVpDEEYoOodKqMaNpdJwOh0lNhuOS/jVE+v4Vdo5mcCeYhmdE9Ub7AODTpowiYcfhllDdMrZir4qqRo/GmbhWM6nrTJqNkMVrU/JAz8bs+vltdjh7BpWVObMkQBsXzwHoCva0Fi4Xw+Av4Lwd9uwDVOh52ViJii1gvs8dSIqQtfKrmIwfHrO/49bkx4uW4WwFGMoRFDQh+KcoduIow+T+sXjpOjRRoNjwFqX1MaX//DGSd4YV4IneWPw03GR9GlZll+R/qUADZv7i3J5SH8P7tYVA8hma4SkPhEDokF0VlcZ0Qp7onvPyXgnat20HMDYg9gHJMmv7viRBHzixRsOnKFkkcYGK0yeM9q89DLbekTsD/icHcBbMnTlXjfzJSwskBop6moPJ3mws2ZPXUTPYuPT4+MTl2wOEsTVLN9iCNMmxhZ/TTeldHWa81fcy860VJ9F4jMOOWeRj4kHDpjYOWQuCmzkHFWAUwyZTpIynJKqkMRO/jHc2u1dH7aZ8OIoqgg/RiBBRbXAzojSc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
